---
name: GamemodeUI
main: Angga7Togk\GamemodeUI\Main
version: 1.0
api: 4.0.0
author: Angga7Togk
description: "Open GamemodeUI"

permissions:
  gamemodeui.use:
    description: "GamemodeUI Permission"
    default: op
  gamemodeui.use.creative:
    description: "GamemodeUI Creative Permission"
    default: op
  gamemodeui.use.survival:
    description: "GamemodeUI Survival Permission"
    default: op
  gamemodeui.use.adventure:
    description: "GamemodeUI Adventure Permission"
    default: op
  gamemodeui.use.spectator:
    description: "GamemodeUI Spectator Permission"
    default: op
